# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fca5d443c40503499b2741db26c8ff3969287fc2c666da7bda26ca073b557c7f4a324a4f4f87888f0ac6044a78c9e8c3976e51472e4195b94c4cf04cdedf214

test:
  secret_key_base: ef14da948244bd8645365c4776a51ecb74995579b6cf4b800ebcaf6ccdfabf7c55ba43e455c1fff7d54f37499b8b17a4392e950d9cd59da3fbcb29550b9b4419

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
